# Generated by Django 4.1.5 on 2023-01-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='crm_api.contract'),
            preserve_default=False,
        ),
    ]
