# Generated by Django 4.1.5 on 2023-01-10 16:51

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'CustomUser')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    view_client = Permission.objects.get(codename='view_client')
    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    view_contract = Permission.objects.get(codename='view_contract')
    add_event = Permission.objects.get(codename='add_event')
    view_user = Permission.objects.get(codename='view_customuser')

    sales_permissions = [
        add_client,
        change_client,
        view_client,
        add_contract,
        change_contract,
        view_contract,
        add_event,
        view_user,
    ]

    sales = Group(name='sales')
    sales.save()
    sales.permissions.set(sales_permissions)

    change_event = Permission.objects.get(codename='change_event')
    view_event = Permission.objects.get(codename='view_event')

    support_permissions = [
        view_client,
        change_event,
        view_event,
        view_user,
    ]
    support = Group(name='support')
    support.save()
    support.permissions.set(support_permissions)

    add_user = Permission.objects.get(codename='add_customuser')
    change_user = Permission.objects.get(codename='change_customuser')
    delete_user = Permission.objects.get(codename='delete_customuser')

    management_permissions = [
        add_user,
        change_user,
        view_user,
        delete_user,
        change_client,
        change_contract,
        change_event,
        view_client,
        view_contract,
        view_event,
    ]
    management = Group(name='management')
    management.save()
    management.permissions.set(management_permissions)

    for user in User.objects.all():
        if user.role == 'SA':
            sales.user_set.add(user)
        if user.role == 'SU':
            support.user_set.add(user)
        if user.role == 'M':
            management.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]

